<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="RiverSystem.ApplicationLayer.Interfaces" />
    <Reference Include="RiverSystem.Persistence" />
    <Reference Include="RiverSystem.PreProcessing" />
    <Reference Include="RiverSystem.ScenarioExplorer" />
    <Reference Include="RiverSystem" />
    <Reference Include="RiverSystem.PluginManager" />
    <Reference Include="RiverSystem.Api" />
    <Reference Include="RiverSystem.ApplicationLayer.Consumer" />
    <Reference Include="RiverSystem.ApplicationLayer.Consumer.Forms" />
    <Reference Include="RiverSystem.Controls" />
    <Reference Include="RiverSystem.Controls.UI" />
    <Reference Include="RiverSystem.Forms.Core" />
    <Reference Include="RiverSystem.Forms" />
    <Reference Include="RiverSystem.Simulation" />
    <Reference Include="TIME" />
    <Reference Include="TIME.UI" />
    <Reference Include="TIME.ScenarioManagement" />
    <Reference Include="TIME.Tools" />
    <Reference Include="TIME.Winforms" />
    <Reference Include="TIME.Winforms.UI" />
    <Reference Include="NetronGraphLib" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CoreWCF.WebHttp" />
    <PackageReference Include="IronPython" />
    <PackageReference Include="IronPython.Interpreter" />
    <PackageReference Include="IronPython.StdLib" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Data.DataSetExtensions" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.ServiceModel.Primitives" />
    <PackageReference Include="System.ServiceModel.Http" />
    <PackageReference Include="System.ServiceModel.Duplex" />
    <PackageReference Include="System.ServiceModel.NetTcp" />
    <PackageReference Include="System.ServiceModel.Security" />
    <PackageReference Include="System.ServiceModel.Federation" />
    <!-- Required to match RiverSystem.Controls.UI-->
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Lib\**\*" />
    <!-- <AppDesigner Include="Properties\" /> -->
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Logo_RGB.png" />
    <Resource Include="Resources\*.*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\NodeIcons\*.*" />
  </ItemGroup>
</Project>