<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <!-- Don't copy local and only include "compile" assets -->
    <ProjectReference Include="..\FlowMatters.Source.Veneer\FlowMatters.Source.Veneer.csproj">
      <Private>False</Private>
      <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile</IncludeAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RiverSystem" Private="False" />
    <Reference Include="RiverSystem.ApplicationLayer" Private="False" />
    <Reference Include="RiverSystem.ApplicationLayer.Interfaces" Private="False" />
    <Reference Include="RiverSystem.Persistence" Private="False" />
    <Reference Include="RiverSystem.PluginManager" Private="False" />
    <Reference Include="TIME" Private="False" />
    <Reference Include="TIME.ScenarioManagement" Private="False" />
    <Reference Include="TIME.Tools" Private="False" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Nito.AsyncEx" />
  </ItemGroup>
  <ItemGroup>
     <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None> 
  </ItemGroup>
</Project>