<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Nito.AsyncEx" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlowMatters.Source.Veneer\FlowMatters.Source.Veneer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="RiverSystem" />
    <Reference Include="RiverSystem.ApplicationLayer" />
    <Reference Include="RiverSystem.ApplicationLayer.Interfaces" />
    <Reference Include="RiverSystem.Persistence" />
    <Reference Include="RiverSystem.PluginManager" />
    <Reference Include="TIME" />
    <Reference Include="TIME.ScenarioManagement" />
    <Reference Include="TIME.Tools" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>